package pdf

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/oernster/symdiary/internal/domain"
)

// aMark answers a small PNG standing in for the application's icon, built here
// so the test needs no file of its own to keep in step with the real one.
func aMark(t *testing.T) []byte {
	t.Helper()
	square := image.NewRGBA(image.Rect(0, 0, 8, 8))
	for x := 0; x < 8; x++ {
		for y := 0; y < 8; y++ {
			square.Set(x, y, color.RGBA{R: 20, G: 120, B: 90, A: 255})
		}
	}
	var out bytes.Buffer
	if err := png.Encode(&out, square); err != nil {
		t.Fatalf("encoding the mark: %v", err)
	}
	return out.Bytes()
}

// aRecord answers a record long enough to run past one page.
func aRecord(events int) []domain.Line {
	lines := []domain.Line{
		{Kind: domain.LineProvenance, Text: "Generated by SymDiary (https://symdiary.com)"},
		{Kind: domain.LineTitle, Text: "SYMPTOM RECORD"},
		{Kind: domain.LineRange, Text: "23 August - 22 September 2026"},
		{Kind: domain.LineStatement, Text: "This record is not a diagnosis."},
		{Kind: domain.LineHeading, Text: "Tired - many recorded events"},
	}
	for i := 0; i < events; i++ {
		lines = append(lines,
			domain.Line{Kind: domain.LineWhen, Text: "22 Sep 17:12"},
			domain.Line{Kind: domain.LineSeverity, Text: "Severity: Moderate"},
			domain.Line{Kind: domain.LineNote, Text: "Only been awake for about 10 minutes."},
		)
	}
	return lines
}

// write draws a record into the test's own folder, answering the path and the
// pages it came to.
func write(t *testing.T, sheet Sheet, lines []domain.Line) (string, int) {
	t.Helper()
	path := filepath.Join(t.TempDir(), "record.pdf")
	pages, err := sheet.Write(path, lines)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	return path, pages
}

func TestTheRecordIsWrittenAsAPDF(t *testing.T) {
	t.Parallel()
	path, pages := write(t, Sheet{Mark: aMark(t)}, aRecord(4))

	if pages != 1 {
		t.Errorf("a short record came to %d pages, want 1", pages)
	}
	// A reader takes this to an appointment, so it has to be a document a
	// machine they have never met will open.
	written, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading what was written: %v", err)
	}
	if !bytes.HasPrefix(written, []byte("%PDF-")) {
		t.Error("what was written is not a PDF")
	}
	if len(written) < 1000 {
		t.Errorf("the document is %d bytes, which is too small to hold a record", len(written))
	}
}

func TestALongRecordRunsToSeveralPages(t *testing.T) {
	t.Parallel()
	_, pages := write(t, Sheet{}, aRecord(120))

	if pages < 2 {
		t.Errorf("120 events came to %d page(s), want more than one", pages)
	}
	// The count is what the footer states, so a wrong one would number every
	// page against a total that does not exist.
	if want := len(Pages(aRecord(120), fontWidths{doc: newDoc()})); pages != want {
		t.Errorf("the document holds %d pages and the layout made %d", pages, want)
	}
}

func TestARecordWithNoMarkIsStillWritten(t *testing.T) {
	t.Parallel()
	// A missing mark is the absence of a decoration, never a reason to refuse
	// somebody their own medical record.
	path, pages := write(t, Sheet{}, aRecord(2))
	if pages != 1 {
		t.Errorf("came to %d pages, want 1", pages)
	}
	if info, err := os.Stat(path); err != nil || info.Size() == 0 {
		t.Errorf("no document was written without a mark: %v", err)
	}
}

func TestARecordOfNothingIsRefusedRatherThanWritten(t *testing.T) {
	t.Parallel()
	// An empty PDF is a file a reader would carry to an appointment and find
	// blank. Saying so beats handing them one.
	path := filepath.Join(t.TempDir(), "nothing.pdf")
	pages, err := Sheet{}.Write(path, nil)

	if err == nil {
		t.Fatal("an empty record was written, want a refusal")
	}
	if pages != 0 {
		t.Errorf("an empty record answered %d pages", pages)
	}
	if !strings.Contains(err.Error(), path) {
		t.Errorf("the refusal reads %q and does not name the file", err)
	}
	if _, statErr := os.Stat(path); statErr == nil {
		t.Error("a file was left behind for a record holding nothing")
	}
}

func TestAPathThatCannotBeWrittenIsReported(t *testing.T) {
	t.Parallel()
	// The folder does not exist, which is what a removable drive pulled out
	// between choosing a path and writing to it looks like.
	path := filepath.Join(t.TempDir(), "no-such-folder", "record.pdf")
	if _, err := (Sheet{}).Write(path, aRecord(1)); err == nil {
		t.Error("writing into a folder that is not there answered no error")
	}
}
